services:
  react-green:
    image: my-react-app:latest
    container_name: react-green
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    restart: always
    networks:
      - fullstack-course-app_course-net
networks:
  fullstack-course-app_course-net:
    external: true
