upstream REACT_APP {
    server react-blue:3000;
}

server {
  listen 80;

  location / {
      proxy_pass http://REACT_APP;
      proxy_http_version 1.1;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
  }
}
