pipeline {
  agent any

  environment {
    ACTIVE_FILE = '/tmp/active_version.txt'
    BLUE_APP = 'react-blue:3000'
    GREEN_APP = 'react-green:3000'
    DOCKER_COMPOSE_BLUE = 'docker-compose.blue.yml'
    DOCKER_COMPOSE_GREEN = 'docker-compose.green.yml'
  }

  stages {
    stage('Checkout') {
      steps {
        checkout scm
      }
    }
    
    
    stage('Determine Target') {
      steps {
        script {
          def active = fileExists(ACTIVE_FILE) ? readFile(ACTIVE_FILE).trim() : 'green'
          def target = active == 'blue' ? 'green' : 'blue'
          env.TARGET = target
        }
      }
    }

    stage('Build & Deploy') {
      steps {
        script {
          def composeFile = env.TARGET == 'blue' ? env.DOCKER_COMPOSE_BLUE : env.DOCKER_COMPOSE_GREEN
          sh "docker-compose -f ${composeFile} up -d --build"
        }
      }
    }
    stage('Wait Until Healthy') {
      steps {
        script {
          def healthUrl = env.TARGET == 'blue' ? "http://${env.BLUE_APP}" : "http://${env.GREEN_APP}"

          echo "Waiting for ${healthUrl} to become healthy..."
          retry(3) { // try up to 20 times (approx 20 seconds)
            sleep 1
            def code = sh(script: "curl -s -o /dev/null -w \"%{http_code}\" ${healthUrl}", returnStdout: true).trim()
            if (code != '200') {
              error("Health check failed with code ${code}")
            }
          }
        }
      }
    }

    stage('Switch Nginx Proxy') {
      steps {
        script {
          def backend = env.TARGET == 'blue' ? env.BLUE_APP : env.GREEN_APP
          sh "./jenkins/scripts/switch_nginx.sh ${backend} ${env.ACTIVE_FILE}"
          writeFile file: ACTIVE_FILE, text: env.TARGET
        }
      }
    }
  }
}
