pipeline {
  agent any

    tools {
    nodejs 'Node 20'           
    }
  environment {
    CI = true
    SCANNER_HOME = tool 'sonar-scanner'
  }

 
  stages {
    stage('Checkout') {
      steps {
        checkout scm
      }
    }
    stage('Build Frontend') {
        steps {
            sh 'npm install'
            sh 'npm build'
        }
    }
    stage("OWASP Scan") {
        steps {
            dependencyCheck additionalArguments: '--scan ./', odcInstallation: 'DP'
            dependencyCheckPublisher pattern: '**/dependency-check-report.xml'
        }
    }
    stage("Sonarqube Check"){
        steps {
            withSonarQubeEnv('sonar-server') {
                sh '''
                    $SCANNER_HOME/bin/sonar-scanner -Dsonar.projectName=React-App \
                    -Dsonar.java.binaries=. \
                    -Dsonar.projectKey=React-App
                '''
            }
        }
    }

    stage("Login Docker Hub") {
         steps {
                withCredentials([usernamePassword(credentialsId: '9bbf88f7-54fb-4234-b7a0-03d164813d1a', usernameVariable: 'DOCKER_USER', passwordVariable: 'DOCKER_PASS')]) {
                    sh 'echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin'
                }
            }
    }
    stage("Build & Push Docker Image"){
        steps {
           sh 'docker build -t react-app:latest ../../'
           sh 'docker tag tanle/react-app:latest'
           sh 'docker push tanle/react-app:latest'
        }
    }
  }
}
