pipeline {
  agent any
    tools {
        nodejs 'Node23'           
    }
  environment {
    CI = true
    SCANNER_HOME = tool 'sonar-scanner'
  }

 
  stages {
    stage('Checkout') {
      steps {
        checkout scm
      }
    }
    stage('Build Frontend') {
        steps {
            sh 'npm install'
            sh 'npm run build'
        }
    }
    stage("OWASP Scan") {
        steps {
            dependencyCheck additionalArguments: '--scan ./', odcInstallation: 'DP'
            dependencyCheckPublisher pattern: '**/dependency-check-report.xml'
        }
    }
    stage("Sonarqube Check"){
        steps {
            withSonarQubeEnv('sonar-server') {
                sh '''
                    $SCANNER_HOME/bin/sonar-scanner -Dsonar.projectName=React-App \
                    -Dsonar.java.binaries=. \
                    -Dsonar.projectKey=React-App
                '''
            }
        }
    }

    stage("Build & Push Docker Image"){
        steps {
            withDockerRegistry(credentialsId: 'dockerhub', url: 'https://index.docker.io/v1/') {
                  sh 'docker build -t tanle92/react-app:latest .'
                  sh 'docker push tanle92/react-app:latest'
            }

        }
    }
  }
}
